#!/usr/bin/env python3
"""Generate the painted panels that run under the cinematic intro.

    export GEMINI_API_KEY=...
    python3 tools/gen_panels.py            # only what is missing
    python3 tools/gen_panels.py --force    # all of them again
    python3 tools/gen_panels.py --only war today

Calls Gemini 2.5 Flash Image ("nano banana"). Several panels are image-to-image
from the photographs in refs/, so the town in the painting is the actual town
and the aircraft is the actual aircraft; the rest are painted from the prompt.

Raw returns are kept in refs/panels/ so a good one is never regenerated by
accident. The build copies are 1280x720 WebP in build/payload/, which is what
gets inlined.

On style: the brief was "Ghibli-ish". These prompts describe the aesthetic —
hand-painted anime film backgrounds, gouache, warm Mediterranean light —
rather than naming a studio. It gets the same look and it is a better prompt.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
REFS = ROOT / "refs"
PANELS = REFS / "panels"
OUT = ROOT / "build" / "payload"

MODEL = os.environ.get("FR_IMAGE_MODEL", "gemini-2.5-flash-image")
ENDPOINT = ("https://generativelanguage.googleapis.com/v1beta/models/"
            "%s:generateContent")

# The house style, prepended to every prompt. Keeping it in one place is what
# stops nine panels looking like nine different films.
STYLE = (
    "Hand-painted anime feature-film background art. Soft gouache and "
    "watercolour on paper, visible brushwork, gentle cel-shaded forms, no "
    "outlines on the landscape, warm luminous Mediterranean light, richly "
    "saturated but natural colour, painterly cumulus clouds, fine detail in "
    "the foliage and the stonework. Cinematic wide composition, horizon low, "
    "no text, no lettering, no watermark, no signature. "
)

# (key, source ref or None, prompt)
PANELS_SPEC = [
    ("war", "Šibenik_panorama_from_fortress.jpg",
     "Repaint this view of the Dalmatian coastal town in the style above, but "
     "at night in the winter of 1992: the stone town dark and shuttered under "
     "a cold indigo sky, a few orange fires burning in the hills across the "
     "bay, searchlight haze, the sea like black glass. Melancholy, quiet, "
     "no people, no vehicles, no weapons visible. Keep the real skyline — the "
     "fortress on the hill, the cathedral dome, the long harbour."),

    ("orkan", None,
     "A single artillery rocket high in a pale overcast sky above a distant "
     "flat inland city, seen from far away and slightly below. The rocket's "
     "casing has just split open and a wide scattering cloud of two hundred "
     "tiny dark specks is spreading out and beginning to fall, each trailing "
     "a thread-thin white ribbon. Cold morning light, the city small and "
     "hazy far below. Terrible and beautiful and completely silent. No "
     "explosions, no fire, no people."),

    ("jinglebell", None,
     "IMPORTANT: nothing in this frame except sky. No ground, no horizon, no "
     "landscape, no buildings, no trees, no hills. "
     "An extreme close-up study of one small submunition tumbling, filling "
     "most of the frame: a dull olive-grey metal sphere with a serrated band "
     "around its middle and a stubby nose, trailing a long thin white nylon "
     "ribbon that spirals behind it. Behind it only pale blue-white sky and "
     "the soft edge of one cloud, thrown out of focus. Sunlight catching the "
     "metal. Painted with great care, almost tender, like a study of a seed "
     "pod, and all the more frightening for it. No text, no people."),

    ("karst", None,
     "Close low view along a sun-bleached limestone karst hillside above a "
     "blue Adriatic bay. Cracked white rock, tufts of dry thyme and sage, a "
     "few twisted aleppo pines. Lying half-hidden in a crevice, small and "
     "easy to miss, one dull olive-grey metal sphere with a serrated band and "
     "a tattered faded ribbon, weathered, half-buried in dry grass. Hard "
     "summer noon light. Nothing else in the frame. No people, no text."),

    # ("kherson", ...) was cut when the intro was refocused entirely onto
    # Šibenik. The raw is still in refs/panels/ if it is ever wanted back; it
    # is deliberately not built into build/payload any more.

    ("rokici", "rokici-2024-PXL_060824_118634645-3.jpg",
     "Repaint this photograph of the real wildfire in the style above. Keep "
     "the composition exactly: a dense green aleppo-pine hillside filling the "
     "middle of the frame, crowning orange flame breaking along the ridge "
     "line, and enormous billowing smoke — white and grey on the left, heavy "
     "charcoal-black on the right — rising into a hot pale sky. Below and in "
     "front, at the very bottom of the frame, the ordinary edge of a town on "
     "an August afternoon: a crash barrier, a road, a few parked cars. "
     "Painted so the contrast is the whole point — a completely normal "
     "Tuesday with the hillside above it going up. Remove all advertising, "
     "all signage, all lettering and all recognisable faces; keep any figures "
     "tiny, distant and anonymous. No text, no watermark."),

    ("today", "Pogled.na.sibenik.JPG",
     "Repaint this view of the Dalmatian stone town in the style "
     "above, at two in the afternoon in August: blinding white limestone, "
     "terracotta rooftops packed tight, the cathedral's grey barrel roof and "
     "dome at the centre, the turquoise channel and the pine islands beyond, "
     "heat shimmer on the horizon. Brilliant, alive, worth saving. Keep the "
     "real street plan and the real coastline. No text, no people."),

    ("ignition", None,
     "A single small flame taking hold in dry maquis scrub on a white "
     "limestone hillside, a thin column of pale smoke bending sideways in the "
     "wind. Behind and below, far off through the haze, a stone town on a "
     "blue bay, still unaware. Late afternoon, low golden light, long "
     "shadows. Painted with dread. No people, no text."),

    ("canadair", "canadair-flying.jpg",
     "Repaint this yellow and red Canadair CL-415 water bomber in the style "
     "above: banking low and hard over a burning pine hillside on the "
     "Dalmatian coast, wing down, six tonnes of water just released and "
     "falling away as a long white curtain into orange flame and brown smoke. "
     "Three more of the same aircraft small and distant behind it. Turquoise "
     "sea and white karst below. Heroic, urgent, sunlit. Keep the aircraft's "
     "real shape and its yellow fuselage with the red wingtips. No text."),

    ("volley", "dalmatia-sibenik-jadrija-croatia-1-4000x2667u-1024x576.jpg",
     "Repaint this Dalmatian coastal scene in the style above as the closing "
     "shot: late afternoon, the low sun on the water, a Canadair CL-415 "
     "flying straight at the viewer barely above the sea with its scoop "
     "probes down, throwing two long white plumes of spray behind it, the "
     "stone town and the burning hills far ahead. Wide, cinematic, hopeful. "
     "No text, no people."),
]


def call_model(prompt: str, source: Path | None, tries: int = 3) -> bytes:
    parts: list[dict] = [{"text": STYLE + prompt}]
    if source is not None:
        mime = "image/png" if source.suffix.lower() == ".png" else "image/jpeg"
        parts.append({"inline_data": {
            "mime_type": mime,
            "data": base64.b64encode(source.read_bytes()).decode(),
        }})

    body = json.dumps({
        "contents": [{"parts": parts}],
        "generationConfig": {"imageConfig": {"aspectRatio": "16:9"}},
    }).encode()

    key = os.environ.get("GEMINI_API_KEY")
    if not key:
        sys.exit("error: GEMINI_API_KEY is not set")

    last = ""
    for attempt in range(tries):
        req = urllib.request.Request(
            ENDPOINT % MODEL, data=body,
            headers={"content-type": "application/json", "x-goog-api-key": key})
        try:
            with urllib.request.urlopen(req, timeout=180) as r:
                d = json.load(r)
        except urllib.error.HTTPError as e:
            last = "HTTP %s %s" % (e.code, e.read()[:200].decode("utf8", "replace"))
            time.sleep(3 + attempt * 4)
            continue
        except Exception as e:                       # noqa: BLE001
            last = str(e)
            time.sleep(3 + attempt * 4)
            continue

        cands = d.get("candidates") or []
        for c in cands:
            for p in c.get("content", {}).get("parts", []):
                if "inlineData" in p:
                    return base64.b64decode(p["inlineData"]["data"])
        # A refusal or a text-only answer: worth seeing rather than swallowing.
        txt = " ".join(p.get("text", "") for c in cands
                       for p in c.get("content", {}).get("parts", []))
        last = "no image returned. %s" % (txt[:200] or json.dumps(d)[:200])
        time.sleep(2)
    raise RuntimeError(last)


def to_payload(raw: Path, dest: Path, width=1280, height=720):
    """Crop to 16:9 and write the WebP the build inlines."""
    im = Image.open(raw).convert("RGB")
    want = width / height
    have = im.width / im.height
    if have > want:
        w = int(im.height * want)
        im = im.crop(((im.width - w) // 2, 0, (im.width - w) // 2 + w, im.height))
    elif have < want:
        h = int(im.width / want)
        im = im.crop((0, (im.height - h) // 2, im.width, (im.height - h) // 2 + h))
    im = im.resize((width, height), Image.LANCZOS)
    dest.parent.mkdir(parents=True, exist_ok=True)
    im.save(dest, "WEBP", quality=82, method=6)
    return dest.stat().st_size


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--only", nargs="*", default=None)
    ap.add_argument("--repack", action="store_true",
                    help="skip the model, just rebuild the WebPs from refs/panels")
    args = ap.parse_args()

    PANELS.mkdir(parents=True, exist_ok=True)
    print("panels via %s" % MODEL)

    for key, ref, prompt in PANELS_SPEC:
        if args.only and key not in args.only:
            continue
        raw = PANELS / ("%s.png" % key)
        dest = OUT / ("panel_%s.webp" % key)

        if not raw.exists() or (args.force and not args.repack):
            if args.repack:
                print("  %-11s missing raw, skipped" % key)
                continue
            src = None
            if ref:
                src = REFS / ref
                if not src.exists():
                    print("  %-11s ref missing: %s" % (key, ref))
                    src = None
            try:
                data = call_model(prompt, src)
            except Exception as e:                   # noqa: BLE001
                print("  %-11s FAILED  %s" % (key, e))
                continue
            raw.write_bytes(data)

        size = to_payload(raw, dest)
        print("  %-11s %5.0f KB  %s" % (key, size / 1024,
                                        ("from " + ref) if ref else "painted"))


if __name__ == "__main__":
    main()
