// -----------------------------------------------------------------------------
// Flamme Retardé — a Canadair CL-415 over Šibenik
//
// The terrain is the real one: public elevation data for the bay, OpenStreetMap
// for the coastline, the land cover and the footprints of the old town. Every
// pixel drawn on top of that — the karst, the pines, the roofs, the sea, the
// fire and the aircraft — is generated by code at load time.
// -----------------------------------------------------------------------------

const CONFIG = {
  seed: 0x51be_1470,           // "šibenik" if you squint

  // ── the world ───────────────────────────────────────────────────────────
  // 13 km square. Origin sits between Jadrija and the old town so the whole
  // fight — sea, channel, city, hills — is inside the near half of the view.
  world: 13000,
  hfRes: 1024,                 // terrain samples per side, 12.7 m apart
  seaLevel: 0,

  // Where the baked DEM window sits (see tools/bake.py — must agree)
  originLat: 43.7280,
  originLon: 15.8700,

  // ── the fire ────────────────────────────────────────────────────────────
  fireRes: 256,                // automaton cells per side, ~50.8 m each
  fireStep: 0.25,              // seconds between automaton ticks
  ignitionPoint: [-1500, -60],    // the bomblet, in the scrub NE of Jadrija
  fireSpreadBase: 0.048,       // per-tick probability into a neighbour
  fuelBurnRate: 0.055,         // fuel consumed per second at full intensity
  waterPerCell: 900,           // litres to knock a cell down from full

  // ── the aircraft ────────────────────────────────────────────────────────
  tankCapacity: 6137,          // litres — the real CL-415 figure
  scoopRate: 512,              // l/s → a full load in ~12 s, also the real one
  scoopMaxAlt: 14,             // metres above the water
  // The low end used to be 58, which is above the speed a full-throttle
  // aeroplane actually settles at with the probes down and six tonnes coming
  // aboard — the scoop cut out halfway through every run, for the player as
  // well as the autopilot. 52 still leaves a margin over the 46 m/s stall.
  scoopSpeed: [52, 108],       // m/s window in which the probes will bite
  dropRate: 3400,              // l/s when the doors are open
  emptyMass: 12880,            // kg
  wingspan: 28.6,
  fuselage: 19.82,

  // ── presentation ────────────────────────────────────────────────────────
  // 450 m across the cascade rather than 900: the map is 2048 square either way,
  // so this halves the texel to 0.44 m, and what wants a sharp shadow is the
  // aeroplane and whatever it is parked next to — both of which the cascade is
  // centred on. At 900 the aircraft's own shadow on the apron was visibly
  // stepped from eye height.
  shadowRadius: 450,
  shadowRes: 2048,
  // The near cascade. 900 m across 2048 texels is 44 cm each, which is sized
  // for a hangar and an aeroplane and cannot resolve anything smaller — a
  // bench leg, a car, a person are all far under one texel, and with the PCF
  // spread the softest thing that map can draw is about two and a half metres
  // wide. That is why nothing at Jadrija touched the ground.
  //
  // 110 m across the same 2048 is 5.4 cm, which is a shadow under a chair.
  shadowNearRadius: 55,
  shadowNearRes: 2048,
  startHour: 14.33,
  hourPerSecond: 0.0,          // the light holds; this fight is not about dusk
};

const HALF = CONFIG.world / 2;

// ------------------------------------------------------------------- maths ---

const clamp = (x, a, b) => (x < a ? a : x > b ? b : x);
const lerp = (a, b, t) => a + (b - a) * t;
const sat = (x) => clamp(x, 0, 1);
const TAU = Math.PI * 2;

/** Smooth 0..1 ramp between edges. */
function smoothstep(e0, e1, x) {
  const t = sat((x - e0) / (e1 - e0 || 1e-6));
  return t * t * (3 - 2 * t);
}

/** Frame-rate independent exponential approach. */
const damp = (a, b, lambda, dt) => lerp(a, b, 1 - Math.exp(-lambda * dt));

/** Shortest signed angular difference, radians. */
function angleDelta(a, b) {
  let d = (b - a) % TAU;
  if (d > Math.PI) d -= TAU;
  if (d < -Math.PI) d += TAU;
  return d;
}

/** Deterministic 32-bit PRNG — same seed, same world, every time. */
function mulberry32(seed) {
  let a = seed >>> 0;
  return function rng() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// -------------------------------------------------------------------- noise ---

/** Integer hash -> [0,1). */
function hash2(x, y, seed) {
  let h = Math.imul(x | 0, 0x27d4eb2d) ^ Math.imul(y | 0, 0x165667b1) ^ seed;
  h = Math.imul(h ^ (h >>> 15), 0x2c1b3c6d);
  h = Math.imul(h ^ (h >>> 12), 0x297a2d39);
  return ((h ^ (h >>> 15)) >>> 0) / 4294967296;
}

/** Value noise with quintic interpolation. */
function vnoise(x, y, seed) {
  const xi = Math.floor(x), yi = Math.floor(y);
  const xf = x - xi, yf = y - yi;
  const u = xf * xf * xf * (xf * (xf * 6 - 15) + 10);
  const v = yf * yf * yf * (yf * (yf * 6 - 15) + 10);
  const a = hash2(xi, yi, seed);
  const b = hash2(xi + 1, yi, seed);
  const c = hash2(xi, yi + 1, seed);
  const d = hash2(xi + 1, yi + 1, seed);
  return lerp(lerp(a, b, u), lerp(c, d, u), v) * 2 - 1;
}

/** Fractal Brownian motion, rotating each octave to hide the lattice. */
function fbm(x, y, octaves, seed, lacunarity = 2.03, gain = 0.5) {
  let sum = 0, amp = 0.5, norm = 0;
  let px = x, py = y;
  for (let i = 0; i < octaves; i++) {
    sum += amp * vnoise(px, py, seed + i * 7919);
    norm += amp;
    const nx = px * 0.851 - py * 0.526;
    const ny = px * 0.526 + py * 0.851;
    px = nx * lacunarity;
    py = ny * lacunarity;
    amp *= gain;
  }
  return sum / norm;
}

/** Ridged multifractal — the sharp crests karst weathers into. */
function ridged(x, y, octaves, seed) {
  let sum = 0, amp = 0.5, norm = 0;
  let px = x, py = y;
  for (let i = 0; i < octaves; i++) {
    const n = 1 - Math.abs(vnoise(px, py, seed + i * 6271));
    sum += amp * n * n;
    norm += amp;
    const nx = px * 0.851 - py * 0.526;
    const ny = px * 0.526 + py * 0.851;
    px = nx * 2.07;
    py = ny * 2.07;
    amp *= 0.5;
  }
  return sum / norm;
}

// ------------------------------------------------------- land cover classes ---

// Rasterised from OSM landuse/natural tags. The numbers matter: the fire reads
// FUEL[] and RETAIN[] straight off this map, so what burns and how fast is a
// property of the real land cover around Šibenik, not of a painted mask.
const COVER = {
  SEA: 0, ROCK: 1, GRASS: 2, SCRUB: 3, PINE: 4,
  OLIVE: 5, URBAN: 6, SAND: 7, LAKE: 8, VINE: 9,
};

/** How much there is to burn, 0..1. Bare karst is the natural firebreak. */
const FUEL = [0.00, 0.04, 0.34, 0.78, 1.00, 0.42, 0.22, 0.02, 0.00, 0.30];

/** How well it holds water once wet — high means one drop does lasting good. */
const RETAIN = [1.00, 0.30, 0.55, 0.42, 0.36, 0.62, 0.80, 0.30, 1.00, 0.66];

/** Base ground colour per class, before slope, noise and scorch. */
const COVER_COLOR = [
  [0.05, 0.19, 0.26], // sea (never drawn by terrain, kept for indexing)
  [0.72, 0.69, 0.61], // bare limestone — the white karst
  [0.55, 0.53, 0.34], // dry summer grass
  [0.36, 0.38, 0.26], // maquis
  [0.19, 0.28, 0.19], // aleppo pine
  [0.44, 0.47, 0.37], // olive grove, silver-green
  [0.60, 0.53, 0.46], // town
  [0.84, 0.79, 0.68], // sand and shingle
  [0.10, 0.24, 0.28], // inland water
  [0.46, 0.45, 0.31], // vineyard
];

// ----------------------------------------------------------- shader chunks ---

/** Noise helpers shared by every custom shader in the scene. */
const GLSL_NOISE = /* glsl */ `
const float INV_PI = 0.31830989;
float h21(vec2 p){
  // Wrap before hashing. The world is 13 km across and the sea samples this at
  // ~0.7 cycles/m, so p reaches ~4600; multiplied by 311 that is 1.4e6, where a
  // 24-bit mantissa leaves fract() barely a dozen distinct values and the noise
  // collapses into a fixed lattice you can see from the air. 512 is far larger
  // than any feature we ask for, so the repeat never reads as a repeat.
  p = mod(p, 512.0);
  p = fract(p * vec2(127.317, 311.741));
  p += dot(p, p + 34.129);
  return fract(p.x * p.y);
}
float vnoise2(vec2 p){
  vec2 i = floor(p), f = fract(p);
  f = f * f * (3.0 - 2.0 * f);
  float a = h21(i), b = h21(i + vec2(1.0, 0.0));
  float c = h21(i + vec2(0.0, 1.0)), d = h21(i + vec2(1.0, 1.0));
  return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}
float fbm2(vec2 p, int oct){
  float s = 0.0, a = 0.5, n = 0.0;
  for (int i = 0; i < 7; i++){
    if (i >= oct) break;
    s += a * vnoise2(p);
    n += a;
    p = mat2(1.71, -1.06, 1.06, 1.71) * p;
    a *= 0.5;
  }
  return s / n;
}
float ridge2(vec2 p, int oct){
  float s = 0.0, a = 0.5, n = 0.0;
  for (int i = 0; i < 6; i++){
    if (i >= oct) break;
    float v = 1.0 - abs(vnoise2(p) * 2.0 - 1.0);
    s += a * v * v; n += a;
    p = mat2(1.71, -1.06, 1.06, 1.71) * p;
    a *= 0.5;
  }
  return s / n;
}
float h31(vec3 p){
  p = fract(p * 0.1031);
  p += dot(p, p.yzx + 33.33);
  return fract((p.x + p.y) * p.z);
}
`;

/**
 * The world's lookup tables, shared by terrain, flora, city and the aircraft's
 * shadow. uTerrain packs R = height (m, scaled), G = cover class, B = slope,
 * A = scorch. uFire packs R = intensity, G = fraction of fuel left (1 = never
 * burnt, and 1 for anything that had nothing to burn), B = wetness, A = heat.
 */
const GLSL_TERRAIN = /* glsl */ `
uniform float uTime;
uniform sampler2D uTerrain;
uniform sampler2D uFire;
uniform float uWorldHalf;
uniform float uHeightScale;
uniform float uHeightBias;

vec2 worldToUv(vec2 world){
  return clamp(world / (uWorldHalf * 2.0) + 0.5, 0.0005, 0.9995);
}
vec4 terrainAt(vec2 world){ return texture2D(uTerrain, worldToUv(world)); }
vec4 fireAt(vec2 world){ return texture2D(uFire, worldToUv(world)); }
float heightAt(vec2 world){
  return terrainAt(world).r * uHeightScale + uHeightBias;
}
`;

/**
 * Distance haze. Two things happen here that the valley game did not need: the
 * Mediterranean horizon is far whiter and lower-contrast than an inland one,
 * and the smoke column dyes everything behind it.
 */
const GLSL_HAZE = /* glsl */ `
uniform vec3 uCamPos;
uniform vec3 uHazeNear;
uniform vec3 uHazeFar;
uniform float uHazeDensity;
uniform float uHazeHeight;
uniform vec3 uSmokeTint;
uniform float uSmokeAmt;

vec3 applyHaze(vec3 col, float dist, vec3 worldPos, vec3 sunDir, vec3 viewDir){
  // Height falloff: thick over the water, thin up where we fly.
  float h = exp(-max(worldPos.y - 1.0, 0.0) / uHazeHeight);
  float f = 1.0 - exp(-dist * uHazeDensity * mix(0.5, 1.0, h));
  f = clamp(f, 0.0, 1.0);
  float toward = max(dot(viewDir, sunDir), 0.0);
  vec3 haze = mix(uHazeNear, uHazeFar, smoothstep(0.0, 0.7, f));
  haze += uHazeFar * pow(toward, 16.0) * 0.20;
  haze = mix(haze, uSmokeTint, uSmokeAmt * 0.55);
  return mix(col, haze, f);
}
`;

/**
 * The water column.
 *
 * Haze is one colour and one density and that is right for air, because air
 * takes red, green and blue very nearly equally over the distances anybody can
 * see through it. Water does not. It is a *filter*, and a violently selective
 * one: a metre and a half of Adriatic halves the red and takes about eight per
 * cent of the green, so at six metres a red swimsuit is brown, at ten it is
 * black, and the reason everything down there is turquoise is not that anybody
 * tinted it — it is that turquoise is the only light left.
 *
 * `uWaterK` is that, as a diffuse attenuation coefficient per metre per
 * channel. The numbers come from Jerlov's optical water types, which are the
 * standard oceanographic classification and have been since 1968: type I is
 * the open Pacific, III the murkiest ocean, and 1C–9C the coastal series. The
 * Adriatic off Šibenik in August is oligotrophic and very clear — a coastal 1C
 * — and this is that: red 0.38, green 0.052, blue 0.072. Green carries
 * furthest because there is enough dissolved matter here to beat blue, which
 * is the whole difference between the Adriatic and the tropics; and green and
 * blue are both low enough that the bottom is still there at twenty metres,
 * which is the number that matters, because it is the one you can check by
 * looking at any photograph taken off this coast.
 *
 * Two path lengths, and getting this wrong is the usual way underwater ends up
 * looking like green fog. Light has to come *down* to the thing you are looking
 * at, and then come *back* to your eye. So a rock ten metres down seen from
 * eight metres away has travelled eighteen metres of water and not eight, and
 * that is why a seabed goes blue-black with depth even when it is close enough
 * to touch.
 */
const GLSL_WATER = /* glsl */ `
uniform vec3 uWaterK;
uniform vec3 uWaterFog;
uniform float uCamDepth;

/** How much of the eye-to-point segment is actually under the surface. */
float waterPath(vec3 p, float dist){
  float y0 = uCamPos.y, y1 = p.y;
  if (y1 >= 0.0) return 0.0;
  if (y0 <= 0.0) return dist;
  return dist * (-y1) / max(y0 - y1, 1e-4);
}

/**
 * col is what the surface would look like in air; dist is the eye-to-point
 * distance and p the point, whose own depth is the downward path. (No
 * backticks in here: this is inside a template literal and one would end it.)
 */
vec3 applyWater(vec3 col, float dist, vec3 p){
  float wet = waterPath(p, dist);
  if (wet <= 0.0) return col;
  float down = max(0.0, -p.y);
  // Down: what the light had left by the time it got there.
  // 0.85 and not 1.0 because the sun is not overhead and, more to the point,
  // a good deal of what lights the bottom got there by scattering rather than
  // by falling straight down. A strictly vertical path over-darkens the
  // shallows, which is how three metres of water ends up looking like ten.
  col *= exp(-uWaterK * down * 0.85);
  // Back: what survived the swim to the eye, and what scattered in on the way.
  vec3 T = exp(-uWaterK * wet);
  // The inscatter is itself lit through the column over the *viewer's* head,
  // which is what makes going deep go dark rather than merely go blue.
  vec3 fog = uWaterFog * exp(-uWaterK * max(0.0, uCamDepth) * 0.85);
  return mix(fog, col, T);
}
`;

// ------------------------------------------------------------- sun & sky -----

/**
 * Palette stops keyed on sun elevation. Tuned for the Dalmatian coast in
 * August: a harder, whiter sun than an inland valley gets, a zenith that stays
 * saturated well past noon, and a horizon that bleaches out over the sea.
 *
 * `ambI` was raised across the daylight stops once there was a way to stand in
 * shade. The scene-linear ratio between sun and sky was defensible — about 7:1,
 * against a real 8:1 for a horizontal surface at this elevation — but ACES has a
 * long toe, so a correct 7:1 arrived on screen as 35:1 and open shade measured
 * 21/255 against sunlit concrete at 143. That is not what a shadow on a white
 * promenade looks like in August. The sun term barely moves, because ambient is
 * a sixth of a sunlit surface and all of a shaded one, which is exactly the
 * property that makes this the right knob rather than the exposure.
 *
 * `ambGround` went up with it on the two daylight stops for a reason specific to
 * here: the hemispheric model's lower half is standing in for whatever is under
 * you, and around this bay that is bare limestone karst and a very bright sea,
 * not soil. It is the half that lights a vertical surface, so it is what a wall
 * with its back to the sun is actually lit by.
 */
const SKY_STOPS = [
  {
    elev: 62,
    zenith: [0.129, 0.318, 0.671], horizon: [0.741, 0.831, 0.882],
    sun: [1.000, 0.984, 0.945], sunI: 3.35,
    ambSky: [0.412, 0.545, 0.729], ambGround: [0.447, 0.424, 0.351], ambI: 1.25,
    hazeNear: [0.706, 0.788, 0.843], hazeFar: [0.796, 0.855, 0.894],
    density: 0.000072, night: 0.0,
  },
  {
    elev: 36,
    zenith: [0.157, 0.361, 0.702], horizon: [0.784, 0.839, 0.867],
    sun: [1.000, 0.965, 0.886], sunI: 3.05,
    ambSky: [0.404, 0.529, 0.706], ambGround: [0.435, 0.408, 0.331], ambI: 1.16,
    hazeNear: [0.729, 0.788, 0.827], hazeFar: [0.820, 0.855, 0.878],
    density: 0.000086, night: 0.0,
  },
  {
    elev: 14,
    zenith: [0.196, 0.392, 0.686], horizon: [0.898, 0.808, 0.678],
    sun: [1.000, 0.882, 0.702], sunI: 2.70,
    ambSky: [0.427, 0.510, 0.651], ambGround: [0.404, 0.353, 0.271], ambI: 1.02,
    hazeNear: [0.796, 0.792, 0.761], hazeFar: [0.890, 0.847, 0.769],
    density: 0.000112, night: 0.0,
  },
  {
    elev: 3,
    zenith: [0.196, 0.333, 0.596], horizon: [0.949, 0.667, 0.443],
    sun: [1.000, 0.686, 0.408], sunI: 2.05,
    ambSky: [0.404, 0.443, 0.580], ambGround: [0.365, 0.290, 0.212], ambI: 0.86,
    hazeNear: [0.812, 0.718, 0.655], hazeFar: [0.929, 0.737, 0.580],
    density: 0.000142, night: 0.03,
  },
  {
    elev: -4,
    zenith: [0.145, 0.224, 0.463], horizon: [0.855, 0.435, 0.361],
    sun: [0.941, 0.451, 0.302], sunI: 0.55,
    ambSky: [0.302, 0.329, 0.502], ambGround: [0.282, 0.208, 0.184], ambI: 0.62,
    hazeNear: [0.635, 0.510, 0.522], hazeFar: [0.784, 0.478, 0.416],
    density: 0.000165, night: 0.20,
  },
  {
    elev: -12,
    zenith: [0.043, 0.071, 0.184], horizon: [0.192, 0.180, 0.286],
    sun: [0.282, 0.247, 0.333], sunI: 0.04,
    ambSky: [0.110, 0.145, 0.271], ambGround: [0.094, 0.094, 0.129], ambI: 0.36,
    hazeNear: [0.184, 0.184, 0.263], hazeFar: [0.224, 0.208, 0.302],
    density: 0.000150, night: 0.85,
  },
];

/** Linear-interpolate the palette table at a given sun elevation. */
function skyStateAt(elevDeg) {
  const s = SKY_STOPS;
  let i = 0;
  while (i < s.length - 2 && elevDeg < s[i + 1].elev) i++;
  const a = s[i], b = s[i + 1];
  const t = sat((a.elev - elevDeg) / (a.elev - b.elev));
  const mix3 = (p, q) => [lerp(p[0], q[0], t), lerp(p[1], q[1], t), lerp(p[2], q[2], t)];
  return {
    zenith: mix3(a.zenith, b.zenith),
    horizon: mix3(a.horizon, b.horizon),
    sun: mix3(a.sun, b.sun),
    sunI: lerp(a.sunI, b.sunI, t),
    ambSky: mix3(a.ambSky, b.ambSky),
    ambGround: mix3(a.ambGround, b.ambGround),
    ambI: lerp(a.ambI, b.ambI, t),
    hazeNear: mix3(a.hazeNear, b.hazeNear),
    hazeFar: mix3(a.hazeFar, b.hazeFar),
    density: lerp(a.density, b.density, t),
    night: lerp(a.night, b.night, t),
  };
}

/**
 * Sun position for Šibenik — 43.73°N — in the second week of August. Rises
 * about 05:50, sets about 20:10, and tops out just under 65°, which is why the
 * karst is blinding and the shadows are short.
 */
function sunAngles(hour) {
  const rise = 5.85, set = 20.15;
  const day = (hour - rise) / (set - rise);
  const elev = 64.5 * Math.sin(Math.PI * clamp(day, -0.3, 1.3));
  // ENE through south to WNW.
  const az = THREE.MathUtils.degToRad(66 + 228 * clamp(day, -0.18, 1.18));
  const e = THREE.MathUtils.degToRad(elev);
  return {
    elev,
    dir: new THREE.Vector3(
      Math.cos(e) * Math.sin(az),
      Math.sin(e),
      Math.cos(e) * Math.cos(az),
    ).normalize(),
  };
}

function formatClock(sec) {
  const m = Math.floor(sec / 60), s = Math.floor(sec % 60);
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

/** 7412 -> "7 412" — thousands separated by a thin space, easier to read fast. */
function groupNum(n) {
  return Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
}

// --------------------------------------------------------- shared uniforms ---

/**
 * One set of uniform objects, shared by reference across every material. Update
 * these once per frame and terrain, sea, flora, city, plane and sky all follow.
 */
const U = {
  uTime: { value: 0 },
  uSunDir: { value: new THREE.Vector3(0.3, 0.85, 0.4).normalize() },
  uSunColor: { value: new THREE.Color(1, 0.98, 0.94) },
  uSunI: { value: 3.3 },
  uAmbSky: { value: new THREE.Color(0.41, 0.55, 0.73) },
  uAmbGround: { value: new THREE.Color(0.36, 0.35, 0.28) },
  uAmbI: { value: 0.56 },
  uZenith: { value: new THREE.Color(0.13, 0.32, 0.67) },
  uHorizon: { value: new THREE.Color(0.74, 0.83, 0.88) },
  uHazeNear: { value: new THREE.Color(0.71, 0.79, 0.84) },
  uHazeFar: { value: new THREE.Color(0.80, 0.86, 0.89) },
  uHazeDensity: { value: 0.000072 },
  uHazeHeight: { value: 260 },
  uNight: { value: 0 },

  // wind — drives the fire, the sea state, the smoke and the aircraft alike
  uWind: { value: new THREE.Vector2(0.87, -0.5) },
  uWindSpeed: { value: 9.0 },

  // world lookups
  uTerrain: { value: null },
  uFire: { value: null },
  uWorldHalf: { value: HALF },
  uHeightScale: { value: 1 },
  uHeightBias: { value: 0 },

  // smoke pall over the whole scene, raised as the fire grows
  uSmokeTint: { value: new THREE.Color(0.42, 0.33, 0.30) },
  uSmokeAmt: { value: 0 },

  uShadowMap: { value: null },
  uShadowMat: { value: new THREE.Matrix4() },
  uShadowTexel: { value: 1 / CONFIG.shadowRes },
  uShadowMapN: { value: null },
  uShadowMatN: { value: new THREE.Matrix4() },
  uShadowTexelN: { value: 1 / CONFIG.shadowNearRes },
  // Which cascades are live this frame, as (far, near). Not a quality dial —
  // a switch. A cascade that is off is not drawn, not aimed, and not sampled,
  // and the branch is on a uniform so the whole warp takes it together. See
  // the three modes in 06-shadow.js.
  uShadowOn: { value: new THREE.Vector2(1, 1) },
  // The needle floor at Jadrija: (centre x, centre z, half-length along the
  // shore, half-width across it), and the shore's own direction as (cos, sin).
  // Written once by 43-jadrija.js when the locale is built; zero until then,
  // and zero is off. See the note in TERRAIN_FRAG.
  uLitter: { value: new THREE.Vector4(0, 0, 0, 0) },
  uLitterAx: { value: new THREE.Vector2(1, 0) },
  uCamPos: { value: new THREE.Vector3() },

  // the water column — see GLSL_WATER
  uWaterK: { value: new THREE.Vector3(0.38, 0.052, 0.072) },
  uWaterFog: { value: new THREE.Color(0.105, 0.375, 0.400) },
  uCamDepth: { value: 0 },
};

/** Uniform bundles, spread into each material that needs them. */
const shareLight = () => ({
  uTime: U.uTime, uSunDir: U.uSunDir, uSunColor: U.uSunColor, uSunI: U.uSunI,
  uAmbSky: U.uAmbSky, uAmbGround: U.uAmbGround, uAmbI: U.uAmbI,
  uZenith: U.uZenith, uHorizon: U.uHorizon, uNight: U.uNight,
});
const shareHaze = () => ({
  uHazeNear: U.uHazeNear, uHazeFar: U.uHazeFar,
  uHazeDensity: U.uHazeDensity, uHazeHeight: U.uHazeHeight,
  uSmokeTint: U.uSmokeTint, uSmokeAmt: U.uSmokeAmt,
});
const shareTerrain = () => ({
  uTerrain: U.uTerrain, uFire: U.uFire, uWorldHalf: U.uWorldHalf,
  uHeightScale: U.uHeightScale, uHeightBias: U.uHeightBias,
});
const shareWater = () => ({
  uWaterK: U.uWaterK, uWaterFog: U.uWaterFog, uCamDepth: U.uCamDepth,
});
const shareShadow = () => ({
  uShadowMap: U.uShadowMap, uShadowMat: U.uShadowMat, uShadowTexel: U.uShadowTexel,
  uShadowMapN: U.uShadowMapN, uShadowMatN: U.uShadowMatN,
  uShadowTexelN: U.uShadowTexelN, uShadowOn: U.uShadowOn,
});

// -------------------------------------------------------------- game state ---

const state = {
  t: 0,                  // seconds since the mission started
  hour: CONFIG.startHour,
  sunElev: 55,
  sky: skyStateAt(55),

  quality: 1,
  fps: 60,
  paused: false,
  phase: 'load',         // load | intro | fly | won | lost

  // the bura, blowing down off the Dinarics toward the sea
  windDir: -0.52,        // radians, direction the wind blows *toward*
  windSpeed: 9.0,
  gust: 0,

  // the aircraft
  water: 0,
  scooping: false,
  dropping: false,
  speed: 0,
  altAgl: 0,

  // the fight
  burning: 0,            // cells alight
  burnt: 0,              // cells consumed
  cityHealth: 1,
  litresDropped: 0,
  litresOnTarget: 0,
  score: 0,
  saved: 0,
};
